#!/usr/bin/env python3
"""
E6 — Security / robustness measurement for CallDNS ZK proofs.

Quantifies the verifier's error rates over many independent trials:

  * FRR  (false reject rate)  — valid proofs that fail to verify.        Expect 0.
  * FAR  (false accept rate)  — invalid proofs that verify anyway.       Expect 0.

Invalid proofs are produced four ways:
  - tamper-s        : increment the response scalar s
  - tamper-R        : flip one byte of the commitment point R
  - swap-pubkey     : substitute a different (valid) public key
  - tamper-metadata : change the metadata bound into the challenge
  - forge-random    : well-formed random points with an unrelated s

A non-zero FAR is a soundness break; a non-zero FRR is a correctness bug.
Both must be exactly 0. Writes a JSON + LaTeX summary to ../calldns-paper/results.

Usage:
  poetry run python scripts/bench_security.py --trials 5000
"""

import argparse
import json
import secrets
from datetime import datetime, timezone
from pathlib import Path

from ecdsa import SECP256k1

from calldns.crypto.crypto_utils import CryptoUtils, ZKProver, ZKVerifier

DEFAULT_OUT = Path(__file__).resolve().parents[2] / "calldns-paper" / "results"
ORDER = SECP256k1.order


def fresh():
    priv, pub, _ = CryptoUtils.generate_keypair()
    return priv, pub


def run(trials):
    prover, verifier = ZKProver(), ZKVerifier()
    meta = {"call_type": "voice", "region": "US"}

    counts = {k: {"tested": 0, "accepted": 0, "rejected": 0}
              for k in ["valid", "tamper_s", "tamper_R", "swap_pubkey",
                        "tamper_metadata", "forge_random"]}

    for _ in range(trials):
        priv, pub = fresh()
        proof = prover.generate_proof(priv, pub, meta)

        # --- valid (FRR) ---
        counts["valid"]["tested"] += 1
        if verifier.verify_proof(proof):
            counts["valid"]["accepted"] += 1
        else:
            counts["valid"]["rejected"] += 1

        # --- tamper s ---
        p = dict(proof); p["s"] = (p["s"] + 1) % ORDER
        _tally(counts["tamper_s"], verifier.verify_proof(p))

        # --- tamper R (flip one byte) ---
        R = bytearray(proof["R"]); R[0] ^= 0x01
        p = dict(proof); p["R"] = bytes(R)
        _tally(counts["tamper_R"], verifier.verify_proof(p))

        # --- swap public key for an unrelated valid one ---
        _, other_pub = fresh()
        p = dict(proof); p["public_key"] = other_pub
        _tally(counts["swap_pubkey"], verifier.verify_proof(p))

        # --- tamper metadata bound into challenge ---
        p = dict(proof); p["metadata"] = {"call_type": "voice", "region": "GB"}
        _tally(counts["tamper_metadata"], verifier.verify_proof(p))

        # --- forge: well-formed random R point + random s, real pubkey ---
        _, rand_pub = fresh()
        rand_R = prover.generate_proof(*fresh(), meta)["R"]  # a valid point, wrong relationship
        p = {"R": rand_R, "s": secrets.randbelow(ORDER - 1) + 1,
             "public_key": rand_pub, "metadata": meta}
        _tally(counts["forge_random"], verifier.verify_proof(p))

    far_categories = ["tamper_s", "tamper_R", "swap_pubkey", "tamper_metadata", "forge_random"]
    total_invalid = sum(counts[k]["tested"] for k in far_categories)
    total_false_accept = sum(counts[k]["accepted"] for k in far_categories)

    return {
        "trials": trials,
        "counts": counts,
        "FRR": counts["valid"]["rejected"] / max(1, counts["valid"]["tested"]),
        "FAR": total_false_accept / max(1, total_invalid),
        "invalid_proofs_tested": total_invalid,
        "false_accepts": total_false_accept,
        "params": {
            "curve": "SECP256k1",
            "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        },
    }


def _tally(slot, accepted):
    slot["tested"] += 1
    slot["accepted" if accepted else "rejected"] += 1


def print_report(r):
    print("\nCallDNS ZK proof security/robustness (E6)")
    print("=" * 60)
    print(f"{'category':<18}{'tested':>10}{'accepted':>10}{'rejected':>10}")
    print("-" * 60)
    for k, v in r["counts"].items():
        print(f"{k:<18}{v['tested']:>10}{v['accepted']:>10}{v['rejected']:>10}")
    print("-" * 60)
    print(f"FRR = {r['FRR']:.6f}   (valid proofs rejected)")
    print(f"FAR = {r['FAR']:.6f}   ({r['false_accepts']}/{r['invalid_proofs_tested']} invalid accepted)")
    ok = r["FRR"] == 0.0 and r["FAR"] == 0.0
    print(f"\nRESULT: {'PASS — FAR=FRR=0' if ok else 'FAIL — non-zero error rate!'}")
    return ok


def latex_table(r):
    return "\n".join([
        "% Auto-generated by scripts/bench_security.py",
        "\\begin{table}[t]\\centering",
        "\\caption{Verifier error rates over %d trials per category.}" % r["trials"],
        "\\label{tab:far-frr}",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Metric & Count & Rate \\\\",
        "\\midrule",
        f"Valid proofs rejected (FRR) & {r['counts']['valid']['rejected']} & {r['FRR']:.4f} \\\\",
        f"Invalid proofs accepted (FAR) & {r['false_accepts']} & {r['FAR']:.4f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])


def main():
    ap = argparse.ArgumentParser(description="CallDNS ZK security/robustness (E6)")
    ap.add_argument("--trials", type=int, default=5000)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--name", default="e6_security")
    ap.add_argument("--no-write", action="store_true")
    args = ap.parse_args()

    r = run(args.trials)
    ok = print_report(r)

    if not args.no_write:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        (args.out_dir / f"{args.name}.json").write_text(json.dumps(r, indent=2))
        (args.out_dir / f"{args.name}.tex").write_text(latex_table(r))
        print(f"\nwrote {args.out_dir / (args.name + '.json')}")

    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
