apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calldns

resources:
  - namespace.yaml
  - configmap.yaml
  - core-node.yaml
  - api.yaml

commonLabels:
  app.kubernetes.io/name: calldns
  app.kubernetes.io/version: "0.2.0"

images:
  - name: calldns
    newTag: latest
